### ISSUE TITLE
Won't work with the Authoring Tool needs "properties.schema"

### ISSUE THREAD

**Issue by mike-st** [cgkineo/adapt-background-switcher#10]
Hi just wondering if anyone has the "properties.schema" for the adapt-background-switcher? I like using it in the developer tool but noticed there is no "properties.schema" to get it to work in the Authoring Tool.

**Comment by moloko** [comment]
not yet, sorry - we work directly with the framework so the properties.schema files only tend to get added as and when we have a bit of spare time, or if we want to formally release a plugin to the community

**Comment by mike-st** [comment]
is there any good documentation you know of on how to create a properties.schema?

**Comment by moloko** [comment]
Sadly not, I have asked a few times for this. 

I usually just end up copying from another plugin that has similar json requirements. 

The [one for contrib-trickle](https://github.com/adaptlearning/adapt-contrib-trickle/blob/master/properties.schema) is probably a good basis for figuring out how to define properties for course.json and blocks.json; [contrib-graphic](https://github.com/adaptlearning/adapt-contrib-graphic/blob/master/properties.schema) will have good examples of settings graphics as properties.

**Comment by mike-st** [comment]
oh okay thanks

**Comment by moloko** [comment]
https://github.com/adaptlearning/adapt_framework/issues/837

Will get onto this in the new year

**Comment by mike-st** [comment]
Hi I have a couple of updates to the Background Switcher in getting it to work with the Authoring Tool. I have been able to upload it successfully into the Authoring tool Plugins area and the input fields are appearing now too for the contentObject and Block areas of the course. One issue is when I am previewing the course it is not adding in the div tags with the BlockSwitcher classes to allow the BG to show. I believe it is related to the  /js/adapt-contrib-background-switcher.js file and it needing to be built to work with the Authoring tool also. Does anyone have any ideas of how to do that or if I am heading in the right direction? Here are the functional bower.json and properties.schema file revisions...

//BOWER.JSON
{
    "name": "adapt-contrib-background-switcher",
    "version": "2.0.0",
    "framework": "^2.0.0",
    "homepage": "https://github.com/adaptlearning/adapt-contrib-background-switcher",
    "authors": [
      "Salamat Ali <salamatmoali@gmail.com>",
      "Stuart O'Hare <develop@stuartohare.com>"
    ],
    "displayName": "Background Switcher",
    "extension": "background-switcher",
    "description": "Switches background image as you move through blocks",
    "main": "/js/adapt-contrib-background-switcher.js",
    "keywords": [
        "adapt-plugin",
        "adapt-extension"
    ],
    "license": "GPL-3.0",
    "targetAttribute": "_backgroundSwitcher"
}


//PROPERTIES.SCHEMA
{
  "type":"object",
  "$schema": "http://json-schema.org/draft-04/schema",
  "id": "http://jsonschema.net",
  "$ref": "http://localhost/plugins/content/component/model.schema",
  "required":false,
  "properties":{
    "pluginLocations": {
      "type":"object",
      "required":true,
      "properties":{
        "config": {
          "type":"object"
        },
        "course": {
          "type":"object"
        },
        "contentobject": {
          "type":"object",
          "properties":{
            "_backgroundSwitcher": {
              "type":"object",
              "required":true,
              "legend": "BackgroundSwitcher",
              "properties":{
                "_isActive": {
                  "type":"boolean",
                  "required":true,
                  "title": "Enabled",
                  "inputType": { "type": "Boolean", "options": [false, true]},
                  "validators": [],
                  "help": "Background Switcher block options object"
                }
              }
            }
          }
        },
        "article": {
          "type":"object"
        },
        "block": {
          "type":"object",
          "properties":{
            "_backgroundSwitcher": {
              "type":"object",
              "required":true,
              "legend": "BackgroundSwitcher",
              "properties":{
                "mobileSrc": {
                  "type":"string",
                  "required":true,
                  "title": "Mobile Background Image Select",
                  "default": "",
                  "inputType": "Asset:image",
                  "validators": ["required"],
                  "help": "This is the background image source used when page is viewed at mobile resolution"
                },
                "src": {
                  "type":"string",
                  "required":true,
                  "title": "Background Image Select",
                  "default": "",
                  "inputType": "Asset:image",
                  "validators": ["required"],
                  "help": "This is the background image source used when page is viewed at desktop resolution"
                }
              }
            }
          }
        },
        "component": {
          "type":"object"
        }
      }
    }
  }
}
![backgroundswitcher2](https://cloud.githubusercontent.com/assets/10455453/12338555/2a773346-bade-11e5-80f4-6821c15a4709.jpg)
![backgroundswitcher1](https://cloud.githubusercontent.com/assets/10455453/12338554/2a7532f8-bade-11e5-924d-d5de2c372ed0.jpg)

**Comment by moloko** [comment]
hi @mike-st thanks for this. it's not normally necessary to make any changes to the javascript in order to make a plugin compatible with the authoring tool - the properties.schema is the main thing to get right as this defines what data is passed to the plugin via the .json

are you able to post a link to a demo of it not working?

**Comment by mike-st** [comment]
Hey thanks once again for your help Matt. Good to know it is in the properties.schema. So the weird thing is when I upload it to the authoring tool it only goes in the plugins folder...
C:\Users\Adapt_Authoring\adapt_authoring\plugins\content\extension\versions\

From what I understand it should be going in the 'temp' folder too but it is not when I upload it...
C:\Users\Adapt_Authoring\adapt_authoring\temp\568aaa1f051f9bac072345d0\adapt_framework\src\extensions\

Here is a zip of the published course...

[test-bg-switcher.zip](https://github.com/cgkineo/adapt-background-switcher/files/92031/test-bg-switcher.zip)

**Comment by mike-st** [comment]
I also noticed in the Published Course file it is not feed the Background Switcher scripts into the adapt.min.js file

**Comment by moloko** [comment]
right, well as you mentioned in an earlier message (which seems to have disappeared) it doesn't look like the code is getting compiled into the output, which is very strange indeed...

I wonder if it's something to do with this line in your properties.schema?
`"$ref": "http://localhost/plugins/content/component/model.schema"`
This is an extension, not a component, so that line shouldn't be there.

**Comment by mike-st** [comment]
Hey yeah I saw that too and removed it form the properties.schema and it still hasn't been working. I also noticed on the bower.json file it was missing the assetFields so I added them into, but still no luck so far. Here are my latest bower and properties.schema
[bower-properties-schema.zip](https://github.com/cgkineo/adapt-background-switcher/files/92464/bower-properties-schema.zip)
 files I am working with...

**Comment by mike-st** [comment]
Hi Have fixed the Background Switcher in the authoring tool and attached the full working package below. Thanks Matt for your help too, it looks like I had it but was caching. Here are the changes I made... 
[adapt-contrib-background-switcher.zip](https://github.com/cgkineo/adapt-background-switcher/files/92570/adapt-contrib-background-switcher.zip)

//background-switcher.less - Fixed max-width to be 100%
.background-switcher-container {
           
            .background-switcher-background {

                background-size: cover;
                background-position: 50% 0;
                position: fixed;
                z-index: 0;
                width: 100%;
                height: 100%;
                top: 50px;                                     
                opacity: 0;
                max-width: 100%;

                transition: opacity 1s;
            }


//BOWER.JSON FILE FIXES
{
    "name": "adapt-contrib-background-switcher",
    "version": "2.0.0",
    "framework": "^2.0.0",
    "homepage": "https://github.com/adaptlearning/adapt-contrib-background-switcher",
    "authors": [
      "Salamat Ali <salamatmoali@gmail.com>",
      "Stuart O'Hare <develop@stuartohare.com>"
    ],
    "displayName": "Background Switcher",
    "extension": "backgroundSwitcher",
    "description": "Switches background image as you move through blocks",
    "main": "/js/adapt-contrib-background-switcher.js",
    "assetFields": [
        "_backgroundSwitcher.src",
        "_backgroundSwitcher.mobileSrc"
    ],
    "keywords": [
        "adapt-plugin",
        "adapt-extension"
    ],
    "license": "GPL-3.0",
    "targetAttribute": "_backgroundSwitcher"
}


//PROPERTIES.SCHEMA FILE FIXES
{
  "type":"object",
  "$schema": "http://json-schema.org/draft-04/schema",
  "id": "http://jsonschema.net",
  "required":false,
  "properties":{
    "pluginLocations": {
      "type":"object",
      "required":true,
      "properties":{
        "config": {
          "type":"object"
        },
        "course": {
          "type":"object"
        },
        "contentobject": {
          "type":"object",
          "properties":{
            "_backgroundSwitcher": {
              "type":"object",
              "required":true,
              "legend": "BackgroundSwitcher",
              "properties":{
                "_isActive": {
                  "type":"boolean",
                  "required":true,
                  "title": "Enabled",
                  "inputType": { "type": "Boolean", "options": [false, true]},
                  "validators": [],
                  "help": "Background Switcher block options object"
                }
              }
            }
          }
        },
        "article": {
          "type":"object"
        },
        "block": {
          "type":"object",
          "properties":{
            "_backgroundSwitcher": {
              "type":"object",
              "required":true,
              "legend": "BackgroundSwitcher",
              "properties":{
                "mobileSrc": {
                  "type":"string",
                  "required":true,
                  "title": "Mobile Background Image Select",
                  "default": "",
                  "inputType": "Asset:image",
                  "validators": ["required"],
                  "help": "This is the background image source used when page is viewed at mobile resolution"
                },
                "src": {
                  "type":"string",
                  "required":true,
                  "title": "Background Image Select",
                  "default": "",
                  "inputType": "Asset:image",
                  "validators": ["required"],
                  "help": "This is the background image source used when page is viewed at desktop resolution"
                }
              }
            }
          }
        },
        "component": {
          "type":"object"
        }
      }
    }
  }
}
