### ISSUE TITLE
background-switcher interferes with load of other pages

### ISSUE THREAD

**Issue by chucklorenz** [cgkineo/adapt-background-switcher#12]
Using the **performance branch**...
Once the page w background-switcher had been visited, other pages failed to load. Error in console log referred to adapt-background-switcher even though the address bar displayed a page id that did not have background-switcher enabled. 

Resolved by adding this line to `onRemove:`
`this.stopListening(Adapt, "pageView:ready", this.onPageReady);`

**Comment by oliverfoster** [comment]
can you check this works as expected?

**Comment by chucklorenz** [comment]
Yep, works as expected. Thnx.
