### ISSUE TITLE
Un register events

### ISSUE THREAD

**Issue by LukaszGrela** [cgkineo/adapt-background-switcher#14]
after fixing the typo in `onRemove` listener it appeared that the extension stops working for second time page with it is visited, it turns out that the events were not unregistered and fired causing the throwing Unhandled Error you could set `listenToOnce` in the `initialize` or call `stopListening` in `onRemove`.

```
            this.listenToOnce(Adapt, "pageView:ready", this.onPageReady);
            this.listenToOnce(Adapt, "remove", this.onRemove);
```

**Comment by moloko** [comment]
should now be fixed by #20
