### ISSUE TITLE
Required causing issues

### ISSUE THREAD

**Issue by hbaileylxd** [cgkineo/adapt-background-switcher#17]
When using this with the new AT0.2.0 and FW2.0.11 there are Required images which are causing articles not to save if you are not using block slider in that article.

I'm not sure if you can just change Required-true to Required-false without causing issues when you do actually want to use it?

**Comment by OscarArango** [comment]
Hello hmaffin, yes, you can change that required setting in schema so that they are not required.  I had to do the same thing for another plugin.

**Comment by oliverfoster** [comment]
resolved https://github.com/cgkineo/adapt-background-switcher/pull/31
