### ISSUE TITLE
Makes next page viewed blank (Framework)

### ISSUE THREAD

**Issue by amypalms** [cgkineo/adapt-background-switcher#19]
When this is applied to a page in the framework, the components and blocks on the next viewed page are blank. They become visible if you refresh the page.

Returning to menu or selecting hyperlink for next page produces same results.

Let me know if you want to see example in action.

**Comment by moloko** [comment]
Thanks for providing the example link (though this seems to have now been removed from the issue?) - in testing that I can see that whenever you navigate away from page2 (the one with backgroundSwitcher enabled) and into another page, there's an error in the console:
`TypeError: this._blockModels is null`
This occurs even if you go back into page2.

Unfortunately the example build you linked to is 'production ready' i.e. all the source code is minified and therefore can't be debugged. Any chance you could upload a 'dev' version?

**Comment by amypalms** [comment]
Hi! Yes I thought the linked course wasn't working but obviously it's fine :)

Which file/ folder shall I upload? The src is far too big...

Thanks so much!

**Comment by moloko** [comment]
Sorry, I meant create a 'dev' version of your course by running `$ grunt dev` then upload the course that's produced as a result of that. The 'dev' switch ensures that 'source mapping' will be including in the course so that's it's possible to debug it.

**Comment by amypalms** [comment]
Ah okay - [this is a dev version](https://www.ole.bris.ac.uk/bbcswebdav/xid-7959112_2)

Thank you!

**Comment by moloko** [comment]
hi @amypalms sorry to take so long to getting round to looking at this, it's been a very busy week!

now I can debug it seems pretty clear that the backgroundSwitcher is not getting disabled when you navigate away from the page it was initialised on... so it then keeps trying to run on pages where it's not supposed to.

If you are using the framework, could you try something for me? in adapt-contrib-background-switcher.js
there's a function called `onRemove`... could you amend that to add `this.remove()` as the last line of the function? i.e. 
```js
onRemove: function () {
	for (var id in this.$blockElements) {
		this.$blockElements[id].off("onscreen", this.callbacks[id]);
	}
	this.$blockElements = null;
	this.$backgroundContainer = null;
	this.$backgrounds = null;
	this._blockModels = null;
	this._blockModelsIndexed = null;
	this._onBlockInview = null;
	this.remove();
}
```

**Comment by amypalms** [comment]
Hi Matt,

Thank you so much! I'm on leave until next week and have no access to the file but will let you know how it goes when I'm back. 

Thanks again!
Amy

**Comment by amypalms** [comment]
Thank you so much Matt - that worked perfectly! 

Amy
