### ISSUE TITLE
performance improvements

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-background-switcher#2]
having any significant amount of code run every time the window.scroll event occurs is not a good idea... one click of the scrollbar's down arrow in Firefox causes the scroll event to fire 9 times, scrolling a notch on the mouse's scroll wheel calls it 22 times with my mouse's scroll settings (which are Windows' default)

should consider using a technique like this instead: http://ejohn.org/blog/learning-from-twitter/

**Comment by oliverfoster** [comment]
Done in rewrite. Handled by onscreen/inview library.
