### ISSUE TITLE
Only last image appearing

### ISSUE THREAD

**Issue by barryjenkin** [cgkineo/adapt-background-switcher#22]
Can't seem to get this to work in the latest authoring tool. Where there are 2 or more blocks using different background images, the last overrides all (none of the preceding ones appear). 
Also it's forcing me to use on every newly created block, even when disabled for the page. Missing image error is displayed when trying to save a new block that doesn't need background switcher.

**Comment by oliverfoster** [comment]
resolved https://github.com/cgkineo/adapt-background-switcher/pull/31
